### ISSUE TITLE
Customization is not supported

### ISSUE THREAD

**Issue by jcc** [vyuldashev/nova-permission#30]
1. How can I show it or set it when I add a column for the permission table?
2. How can I add cards, filters or lenses?
3. How can I update the properties? `eq: title, search`

**Comment by himan72** [comment]
yes will be nice if we can have a config file

**Comment by vyuldashev** [comment]
You can now customize your permission and role resource classes. https://github.com/vyuldashev/nova-permission#customization

If you want to add cards, filters, etc you can extend this package role/permission resources and change what you need.

**Comment by authanram** [comment]
**Remove (or just do not use) shipped navigation entirely:**

1. **Do not add** the `NovaPermissionTool` to your `NovaServiceProvider`
_Expectation: no navigation group/element will be added_

2. Create your own `Permission` and `Role` resources, like the following:
_Expectation: full control - add `Roles` and `Permissions` any place you <3_

```php
// in app/App/Nova/Permission.php (`Role.php` should look like quite similar)

namespace App\Nova;

use Illuminate\Http\Request;
use Vyuldashev\NovaPermission\Permission as NovaPermission;

class Permission extends NovaPermission
{
    // set to `false` at the parent. so this is mandatory to make it visible
    public static $displayInNavigation = true;

    // add the place (group) you <3
    public static $group = 'Some Group';

    public function fields(Request $request)
    {
        //
    }

    // ...
}

```

Hope this helps.

But anyway... i agree with @himan72. (A 🌮 for u buddy... as long we wait for the config file solution)

👍 to your package, by the way. I use it since the first day i use nova. ❤️ ❤️ It's pretty helpful.

**Comment by vyuldashev** [comment]
@authanram I guess your solution is better than the one with config. Extend and make any changes you wish.
