### ISSUE TITLE
Where are roles / permissions on edit / create screen?

### ISSUE THREAD

**Issue by yehudahkay** [vyuldashev/nova-permission#86]
Hi and thank you for the package!

According to https://nova.laravel.com/docs/2.0/resources/relationships.html#searchable-relations a morph to many field should show up on the edit / create screen but I don't see that after installing this package.

Is this a design choice, or possibly an issue with nova or nova docs?

**Comment by vyuldashev** [comment]
Hello. What do you want to be searchable using morph to many field?

**Comment by yehudahkay** [comment]
I would like to edit user permissions on the create update screen as the docs say should work with a morphtomany field, which is the field type used by permissions

**Comment by JoshMoreno** [comment]
Just installed on a bare bones site and am getting the same thing. As @yehudahkay said, it should be showing up on create and edit view according to the docs - https://nova.laravel.com/docs/2.0/resources/relationships.html#morphtomany

Also can't get it to show on the index view.

I'll report back if I figure out what the issue is.
