### ISSUE TITLE
It can't  update or create user data  when use BooleanGroup Field 

### ISSUE THREAD

**Issue by xiyixia** [vyuldashev/nova-permission#98]
Has any guys use the BooleanGroup Field to Attche roles or permissions ? 
i can't update or create data 
````
message: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'roles' in 'field list' (SQL: update `admins` set `roles` = {"1":false,"2":false}, `permissions` = {"1":false}, `admins`.`updated_at` = 2019-11-06 15:33:19 where `id` = 1)",
```

**Comment by iShotFT** [comment]
I'm running into the same issue

**Comment by volkv** [comment]
same. BooleanGroup doesnt work

**Comment by vyuldashev** [comment]
Did you include `Spatie\Permission\Traits\HasRoles` trait to your User model?

**Comment by xiyixia** [comment]
> Did you include `Spatie\Permission\Traits\HasRoles` trait to your User model?

i has include ```Spatie\Permission\Traits\HasRoles``` trait to the User model, but it doesn't work!

**Comment by ITango** [comment]
I have exactly the same error. I did include the Spatie\Permission\Traits\HasRoles trait to the User model.

**Comment by wcjonathan** [comment]
Same issue here, it's because the BooleanGroup is looking for a column called roles on the user table. Whereas roles is a relationship.

**Comment by dylanharbour** [comment]
Same error here. 

Nova documentation  says that Boolean Group is meant for Json fields. It does not seem to be intended for `HasMany` / `MorphMany` style fields. However, because of the magic of eloquent relationships, this looks like it works out of the box. 

However, an eloquent collection is not intended for this field type as far as I know. 

The only working solution I could get was to create a new mutator field which transforms the eloquent relationship into a normal array for a json field. This is much more friendly with the boolean group hydrator. 

e.g. 
```

    /**
     * @return array
     */
    public function getRolesBooleanGroupAttribute()
    {
        return $this->roles()
            ->pluck('name', 'id')
            ->toArray();
    }

    public function setRolesBooleanGroupAttribute($value)
    {
        $roleIds = collect($value)
            ->filter() //removes null values
            ->keys() //get the ids
            ->toArray();

        //syncRoles doesn't like working with Id's, so get the actual objects or role names here. 
        $roles = Role::query()
            ->whereIn('id', $roleIds)
            ->get();

        $this->syncRoles($roles);
    }
```

Then in your nova resource, use it like this. 
```
BooleanGroup::make('Roles', 'roles_boolean_group')->options(
                \Spatie\Permission\Models\Role::get()->pluck('name', 'id')->toArray()
            );
```

It's not the most elegant solution but I think it ticks the box for now (no pun intended)

**Comment by dylanharbour** [comment]
v2.7 released last night of Nova. The following was included which may change the status of the above. I'll test it when I get a gap but that won't be anytime soon. 

`Added ability for BooleanGroup field to use a Collection or Closure to return options @c48980`

**Comment by JoshMoreno** [comment]
Same issue here. BooleanGroup doesn't handle relationships and the closure added in 2.7 doesn't really help here since it's just to define the options. We still need to handle the saving which is the painful part.

My solution right now is this great package, which is really great for all sorts of relationships - https://github.com/dillingham/nova-attach-many

Then in my nova User resource
```php
use NovaAttachMany\AttachMany;
use Vyuldashev\NovaPermission\Permission;
use Vyuldashev\NovaPermission\Role;

// ...

public function fields(Request $request)
{
  return [
    // ...
    AttachMany::make('Roles', 'roles', Role::class),
    MorphToMany::make('Roles', 'roles', Role::class),

    AttachMany::make('Permissions', 'permissions', Permission::class),
    MorphToMany::make('Permissions', 'permissions', Permission::class),
  ];
}
```

**Comment by dylanharbour** [comment]
That looks like a great solution @JoshMoreno . I'll give it a try.

**Comment by gavinhewitt** [comment]
I thought I was doing something wrong, but glad it's not me! Having the same issue.

**Comment by vyuldashev** [comment]
I've just tagged v2.3.0 with new fields which behave like BooleanGroup field. Try them:

```php
use Vyuldashev\NovaPermission\PermissionBooleanGroup;
use Vyuldashev\NovaPermission\RoleBooleanGroup;

public function fields(Request $request)
{
    return [
        // ...
        RoleBooleanGroup::make('Roles'),
        PermissionBooleanGroup::make('Permissions'),
    ];
}
```

**Comment by gavinhewitt** [comment]
Thanks for the quick fix! However, adding permissions to a role seems rather clunky. It could be fixed by adding the PermissionBooleanGroup field to Role.php. Would this be an option?

**Comment by vyuldashev** [comment]
@gavinhewitt Tagged v2.4.0. Added RoleBooleanGroup to Permission resource and PermissionBooleanGroup to Role resource.

**Comment by gavinhewitt** [comment]
@vyuldashev Awesome, thanks!!
